"""empty message

Revision ID: 39dcb6836c60
Revises: e7f256a43ab
Create Date: 2016-03-26 13:42:32.843755

"""

# revision identifiers, used by Alembic.
revision = '39dcb6836c60'
down_revision = 'e7f256a43ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inverts_observation', sa.Column('t0_20', sa.Integer(), nullable=True))
    op.add_column('inverts_observation', sa.Column('t25_45', sa.Integer(), nullable=True))
    op.add_column('inverts_observation', sa.Column('t50_70', sa.Integer(), nullable=True))
    op.add_column('inverts_observation', sa.Column('t75_95', sa.Integer(), nullable=True))
    op.drop_column('inverts_observation', 'transect3')
    op.drop_column('inverts_observation', 'transect2')
    op.drop_column('inverts_observation', 'transect1')
    op.drop_column('inverts_observation', 'transect4')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inverts_observation', sa.Column('transect4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inverts_observation', sa.Column('transect1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inverts_observation', sa.Column('transect2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inverts_observation', sa.Column('transect3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('inverts_observation', 't75_95')
    op.drop_column('inverts_observation', 't50_70')
    op.drop_column('inverts_observation', 't25_45')
    op.drop_column('inverts_observation', 't0_20')
    ### end Alembic commands ###
